language: ruby
cache: bundler
rvm:
  - 2.1.5
env:
  - DB=postgresql
before_script:
  - psql -c 'create database smile_test;' -U postgres
  - cp config/initializers/secret_token_example.rb config/initializers/secret_token.rb
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
